### ISSUE TITLE
What do you need help with?

### ISSUE THREAD

**Issue by Wulfheart** [innocenzi/laravel-vite#1]
I’d like to help to make this project come true. Where can I support you at dev work?

**Comment by innocenzi** [comment]
Hey, I don't really need help right now, but I appreciate you asking. 

I need to change the way the directive work (I don't allow to generate a script directive if the manifest does not exists, which is an issue in development mode) and I need to create a preset, so Vite would be installed and ready after using this command:

```bash
npx apply innocenzi/laravel-vite
```

Those are things I want to do myself. After this, if I need help for things I don't have time to work on, I'll create issues, so if you want to help, you can just go to the issues tab and look for something you want to work on. 

Thanks again :+1:

**Comment by Wulfheart** [comment]
Ok. Can't wait to use it!
