### ISSUE TITLE
@vite not work.

### ISSUE THREAD

**Issue by callmez** [innocenzi/laravel-vite#108]
`Facade\Ignition\IgnitionServiceProvider::registerViewEngines()` will run before `ViteServiceProvider::bootingPackage`
that will let `vite` directive never register in blade compiler.

**Comment by rinodrummer** [comment]
Maybe using `registerPackage()` instead of `bootingPackage()` will fix it.

**Comment by innocenzi** [comment]
@rinodrummer if you have a fix for this I'll let you PR, otherwise I'll revert your previous PR until I can check for myself what's happening.

**Comment by rinodrummer** [comment]
I created a new Laravel project and I'm making some test with the idea I had, but Vite won't load its configuration file.

**Comment by innocenzi** [comment]
I reverted https://github.com/innocenzi/laravel-vite/pull/97. @rinodrummer feel free to try another PR with a regression test if you want, in the meantime I suggest you don't use `@vite` in favor of `{{ vite_tags() }}`.
