### ISSUE TITLE
development mode wont load modules

### ISSUE THREAD

**Issue by mybigman** [innocenzi/laravel-vite#133]
For some reason they wont load the modules?

Laravel app running on `http://localhost:8000`

<img width="1276" alt="image" src="https://user-images.githubusercontent.com/1289916/135428313-9e6d3084-6a03-4851-92a2-61836d40ae31.png">

<img width="305" alt="image" src="https://user-images.githubusercontent.com/1289916/135428396-5e524531-55bf-4427-a84c-1cfadc2b202c.png">

**Comment by innocenzi** [comment]
What's your `vite.config.ts` and `config/vite.php` looking like? That dev server URL seems wrong
