### ISSUE TITLE
Publish vitejs configuration to build assets without needing call to `php artisan`

### ISSUE THREAD

**Issue by mmachatschek** [innocenzi/laravel-vite#137]
It would be awesome to be able to build the vitejs assets without the need to call artisan commands that create the configuration for vite.

E.g. previously when I was building my docker container, I built the JavaScript assets with Laravel Mix in a seperate build step like this: 

```dockerfile
# npm build stage
FROM node:16.10.0-alpine3.14 as buildjs

WORKDIR /app

COPY package.json /app/package.json
COPY package-lock.json /app/package-lock.json

RUN npm ci

COPY src /app

RUN npm run build
```

But now I can't do this anymore because when building the assets with Vite, the laravel-vite plugin calls artisan commands that don't exists in the docker environment/build-step.

To work around this problem I now generate all the configuration that laravel-vite would generate on demand by passing the output of `php artisan vite:config` to the `defineConfig()` method like this (this will skip the step that calls the artisan command):

```js
defineConfig(
    {}, // config variable
    {
        entrypoints: ["resources/scripts/app.ts"],
        aliases: {
            "@":"resources"
        },
        public_directory: "resources/static",
        build_path: "build",
        dev_url: "https://foo.bar,
        asset_plugin: {
            find_regex: "/\\/resources\\/(.*)\\.(svg|jp?g|png|webp)/",
            replace_with: "/resources/$1.$2"
        }
    }
)
```

What I would like to see is a command like `php artisan vite:config --export=path/with/filename.js` that generates the configuration. In the vite.config.ts I'll just pass the relative path to the file and I'll be able to run `npm run build` without php being needed.

Anything that makes the step of manually putting the output of `php artisan vite:config` into the `defineConfig()` method would be appriciated.

I could help out with a PR in the next week if you are interested!

**Comment by innocenzi** [comment]
If I understand correctly, you would like an `export` flag to the `vite:config` command, which would create a JavaScript or JSON file that contains the configuration -- and by configuration, you mean the output of `vite:config`. With that done, you'd import that file in `vite.config.ts` in order to avoid calling PHP at build-time. Is that correct?

**Comment by mmachatschek** [comment]
Exactly 🙌

**Comment by mmachatschek** [comment]
I can do this with the current implementation but would need to write a command on my own. Would be great with this was supported out of the box

**Comment by innocenzi** [comment]
Can you try https://github.com/innocenzi/laravel-vite/tree/feat/config-export and tell me if that works for you?

```
php artisan vite:config --export=vite.config.json
```

```ts
import { defineConfig } from 'laravel-vite'
import config from './vite.config.json'

export default defineConfig({}, config)
```

If that works, I can potentially even auto-detect `vite.config.json` so you don't have to use the ugly `{}, config` parameters.
