### ISSUE TITLE
npx @preset/cli laravel:vite not working in a new laravel project

### ISSUE THREAD

**Issue by IvanBernatovic** [innocenzi/laravel-vite#191]
I installed a fresh Laravel project and ran `npx @preset/cli laravel:vite`. I get this output:

> preset/0.5.3
> 
> Usage:
>   $ preset 
> 
> Commands:
>   apply <resolvable> [target-directory]  Applies the given preset.
>   init [target-directory]                Initializes a new preset.
>                                          
> 
> For more info, run any command with the `--help` flag:
>   $ preset apply --help
>   $ preset init --help
>   $ preset --help
> 
> Options:
>   --reporter <name>  Which reporter to log to.. (default: list)
>   --no-interaction   Disable interactions. Prompts will use their default answers. (default: true)
>   --debug            Use the debug reporter. 
>   -h, --help         Display this help message. 
>   -v, --version      Display the version number. 

Then I tried `npx @preset/cli apply laravel:vite .` based on the command description but then I get this:

> ✘ [ERROR] Could not resolve "apply"
> 
>     ../../../../private/var/folders/2b/dn8t7qp107v187f7_pqc5djm0000gn/T/presets/vite/preset.ts:1:30:
>       1 │ import { Preset, color } from 'apply';
>         ╵                               ~~~~~~~
> 
>   You can mark the path "apply" as external to exclude it from the bundle, which will remove this
>   error.
> 
> 
>  ERROR  Build failed with 1 error:
> ../../../../private/var/folders/2b/dn8t7qp107v187f7_pqc5djm0000gn/T/presets/vite/preset.ts:1:30: ERROR: Could not resolve "apply"

I'm using macOS on Intel CPU, PHP8.1, Node 14 + NPM 8, Laravel 8.

**Comment by innocenzi** [comment]
Hey, sorry - I'm currently migrating everything to `laravel-vite@0.2` and the preset described in the docs is not yet up-to-date. I'm working on it, it will be ready at most tomorrow night.

**Comment by innocenzi** [comment]
I pushed the latest preset. I'll take time to improve it later and make the Inertia preset inherit the Vite one later.

**Comment by jdanino** [comment]
Running into this as well. 

npx @preset/cli apply laravel:vite

I get:
 ERR_CLONE_PRESET  Repository git@github.com:laravel-presets/vite.git could not be cloned.
