### ISSUE TITLE
HttpHeartbeatChecker broken in laravel 9 

### ISSUE THREAD

**Issue by inikoo** [innocenzi/laravel-vite#196]
HttpHeartbeatChecker throw an exception when using Laravel 9

**Comment by nhedger** [comment]
Related to #194

**Comment by nhedger** [comment]
I believe a bug in Laravel's Http Client is responsible for this. I've opened an issue there.

For reference: https://github.com/laravel/framework/issues/40952

**Comment by Esirei** [comment]
I made a PR #194 for this two days ago, you can check the changed file & create a custom HeartBeatChecker.

**Comment by innocenzi** [comment]
Fixed in latest Laravel 8.x and 9.x.
