### ISSUE TITLE
npx @preset/cli laravel:vite not work laravel 9 

### ISSUE THREAD

**Issue by talachart** [innocenzi/laravel-vite#199]
Hello, good morning, I installed Laravel 9, whatever command npx @ preset / cli laravel: vite I press does not work and only prints the following items in the terminal

I'm using WindowsOs on Amd CPU, PHP8.1, Node 16 + NPM 8, Laravel 9.

Usage:
  $ preset

Commands:
  apply <resolvable> [target-directory]  Applies the given preset.
  init [target-directory]                Initializes a new preset.

For more info, run any command with the `--help` flag:
  $ preset apply --help
  $ preset init --help
  $ preset --help

Options:
  --no-interaction  Disable interactions. Prompts will use their default answers. (default: true)
  --debug           Use the debug reporter.
  --silent          Do not use a reporter.
  -h, --help        Display this help message.
  -v, --version     Display the version number.

**Comment by innocenzi** [comment]
Hi, the command is `npx @preset/cli apply laravel:vite`. I probably forgot the `apply` on a documentation somewhere.

**Comment by innocenzi** [comment]
I'll fix the issue on the docs when I come home tomorrow. Thanks for reporting
