### ISSUE TITLE
Incoming features

### ISSUE THREAD

**Issue by innocenzi** [innocenzi/laravel-vite#2]
I'll work on this very soon. Expect the current API to change a bit:

- [x] Automatic entrypoints, inspired by [Vite Rails](https://vite-rails.netlify.app/guide/development.html#entrypoints-%E2%A4%B5%EF%B8%8F)
- [x] Default import alias, inspired by [Vite Rails](https://vite-rails.netlify.app/guide/development.html#import-aliases-%F0%9F%91%89)
- [x] More flexible Blade directives/helpers
- [x] Allow for local development without manifest
- [x] Helper functions
- [x] Move to Pest for testing
- [ ] Setup command
- [ ] Better documentation

**Comment by Wulfheart** [comment]
Hyped.

**Comment by innocenzi** [comment]
I'm tracking this in the PR now.
