### ISSUE TITLE
type="module" not added to production script tags

### ISSUE THREAD

**Issue by georgeboot** [innocenzi/laravel-vite#22]
When loading this package in production mode (`APP_ENV=production`), the code will inject script tags, but the `type="module"` is missing. This results in the browser errorring on the script

The solution should be as easy as altering the following line: https://github.com/innocenzi/laravel-vite/blob/bc2a79936d5dab99abdec24c4b6a045217ea1cb6/src/ManifestEntry.php#L40

**Comment by innocenzi** [comment]
Sorry about that, I'll fix it tonight and make a release. :+1:

**Comment by georgeboot** [comment]
Awesome! Figured I could do a PR as well but since you seem to be working on this relatively active, might be easier to just pull it in yourself :)
