### ISSUE TITLE
Certificate auto-configuration broken with Valet in 0.2.x

### ISSUE THREAD

**Issue by bakerkretzmar** [innocenzi/laravel-vite#223]
In v0.1, automatic certificate configuration used `APP_URL`:

https://github.com/innocenzi/laravel-vite/blob/v0.1.x/npm/src/index.ts#L186

This works, and this behaviour makes sense to me—if Valet serves my project from `site.test`, the certificates are probably for `site.test`, so they'd be at `~/.config/valet/Certificates/site.test.key` etc.

In v0.2, this defaults to using the dev server URL, which is `http(s)://localhost:3000`. This looks for a certificate at `~/.config/valet/Certificates/localhost.key`, which doesn't exist because the site isn't served on `localhost`, it's served on `site.test`.

So omitting the key and cert environment variables as described in the docs (https://laravel-vite.dev/guide/essentials/development.html#using-http-over-tls) doesn't actually work in v0.2 (it results in the same error as #92).

**Comment by innocenzi** [comment]
This totally makes sense. Thanks for catching that.

**Comment by innocenzi** [comment]
I don't have a Mac to test it out, can you please confirm it works with https://github.com/innocenzi/laravel-vite/releases/tag/v0.2.0-beta.9?

**Comment by bakerkretzmar** [comment]
Yep, looks like it's working! Thanks so much for the quick fix!

**Comment by innocenzi** [comment]
You do have to do that once, yes

**Comment by RomkaLTU** [comment]
Or actually set DEV_SERVER_URL same as APP_URL with port :3000 browsers will accept this as valid cert, don't know if that's can cause problems, but working so far.
