### ISSUE TITLE
"ERROR contexts.at is not a function" on npx preset in Homestead

### ISSUE THREAD

**Issue by xcontra** [innocenzi/laravel-vite#224]
Hi, I'm using Laravel 9.0.2 with Homestead as a development environment.
When I try to run `npx @preset/cli apply laravel:vite` from inside Homestead it shows the next error `ERROR  contexts.at is not a function` and it doesn't even start nor shows the actions.

If I run it on Windows using "Git Bash for Windows" only some tasks work (the others fail as expected because PHP and composer are installed inside Homestead) so I need to run it from inside VM.

Is there any solution or way to see the actions the preset will do, so I can execute them manually?

Thanks in advance

**Comment by innocenzi** [comment]
Hello, please update your Node version to the current LTS on your vm. It's a requirement for both the preset and Laravel Vite.
