### ISSUE TITLE
Path of entry points are incorrectly processed

### ISSUE THREAD

**Issue by balthild** [innocenzi/laravel-vite#225]
If I have a Laravel project located at `/app`, all the `/app` that occurred in the path will be removed.

For example, `resources/ts/app.tsx` will become `resources/ts.tsx`.

<img width="260" alt="image" src="https://user-images.githubusercontent.com/2662758/157603805-e1b1d4f2-678e-43df-9ad1-4d8471014a17.png">

This will make Vite fail to build.

**Comment by innocenzi** [comment]
Can you try monkey-patching this https://github.com/innocenzi/laravel-vite/blob/main/src/Configuration.php#L95 with `replaceFirst` and telling me if that works for you?

**Comment by innocenzi** [comment]
Closing this for now, feel free to reopen if you need this solved.

**Comment by masterinfoalberghi** [comment]
You think that this request (manifest public/private URL) could be integrated in the future releases?
