### ISSUE TITLE
Error while building assets using the latest version

### ISSUE THREAD

**Issue by rcerljenko** [innocenzi/laravel-vite#276]
```sh
failed to load config from <project-path>\vite.config.ts
error during build:
Error: Cannot find module 'execa'
```

**Comment by innocenzi** [comment]
Sorry, try beta 20. I've been experimenting with `unbuild` to bundle the plugin and it has caused a few issues with ESM-only dependencies.

**Comment by rcerljenko** [comment]
still the same  :(

**Comment by rcerljenko** [comment]
i think you haven't raised the version inside package.json so it's referenceing the old one?

this is what i've got in my package lock after clean install:
```
"node_modules/vite-plugin-laravel": {
			"version": "0.2.0-beta.19",
			"resolved": "https://registry.npmjs.org/vite-plugin-laravel/-/vite-plugin-laravel-0.2.0-beta.19.tgz",
			"integrity": "sha512-MSdJ0xoVJ4JXnE5rG+ywv0N+bmGK716ltzPCQgG0fLENjgj1fB6ZNBXMDrzYwI98/uR0pR+hV9Xsh3w0ZF2t4Q==",
			"dev": true,
			"dependencies": {
				"debug": "^4.3.4",
				"defu": "^6.0.0"
			}
		},
```

**Comment by rcerljenko** [comment]
sorry i see now that you did.. maybe npm didn't fetch the latest version yet

**Comment by rcerljenko** [comment]
all good now!

**Comment by innocenzi** [comment]
Good to hear! Was scared for a second if that didn't work lol. Thanks for the report

**Comment by rcerljenko** [comment]
thanks for fast fix!  :)  btw laravel is also preparing an official package did you know?

https://github.com/laravel/vite-plugin
