### ISSUE TITLE
@vitejs/plugin-legacy not working

### ISSUE THREAD

**Issue by mrgodhani** [innocenzi/laravel-vite#287]
Hi there,

I am having issues when including @vitejs/plugin-legacy in vite.config.ts

Laravel Vite Version: 0.2.*
Laravel App env: Production

Vite config configuration:

```
import { defineConfig } from 'vite'
import tailwindcss from 'tailwindcss'
import autoprefixer from 'autoprefixer'
import laravel from 'vite-plugin-laravel'
import legacy from "@vitejs/plugin-legacy";

export default defineConfig({
    server: {
        host: '0.0.0.0'
    },
	plugins: [
        legacy({
            targets: ['ie >= 11'],
            additionalLegacyPolyfills: ['regenerator-runtime/runtime']
        }),
		laravel({
			postcss: [
				tailwindcss(),
				autoprefixer(),
			],
		}),
	],
})
```

On running `npm run build` I am getting below manifest error

<img width="812" alt="Screen Shot 2022-06-26 at 9 44 01 AM" src="https://user-images.githubusercontent.com/1529009/175817155-709e3dc4-6825-474e-9ef3-526f18b1b853.png">

Any help or idea?

**Comment by innocenzi** [comment]
I'm afraid it's because of my recent changes with the manifest (https://github.com/innocenzi/laravel-vite/commit/15dff39). It wasn't working with the latest Vite alpha. 

Can you try using `v0.2.0-beta.21` and tell me if it works?

**Comment by mrgodhani** [comment]
@innocenzi  uh oh. Yes, it works with v0.2.0-beta.21

**Comment by innocenzi** [comment]
Thanks - I'll probably revert that commit and wait for https://github.com/vitejs/vite/pull/8768 to be merged.

I'll keep this open in the meanwhile. Very sorry for that!

**Comment by mrgodhani** [comment]
> Thanks - I'll probably revert that commit and wait for [vitejs/vite#8768](https://github.com/vitejs/vite/pull/8768) to be merged.
> 
> I'll keep this open in the meanwhile. Very sorry for that!

No problem great package waiting for when this would get stablized since this was highly tested before Laravel introduced their own official one.

**Comment by innocenzi** [comment]
This has been reverted in https://github.com/innocenzi/laravel-vite/releases/tag/v0.2.0-beta.24, sorry for the inconvenience!
