### ISSUE TITLE
Unexpected token { when creating new project

### ISSUE THREAD

**Issue by matthewknill** [innocenzi/laravel-vite#293]
I wanted to create a new project using Vite, Laravel and Inertia JS. According to [this](https://laravel-vite.dev/guide/extra-topics/inertia.html), it can be done be running the following commands:
```
> composer create-project laravel/laravel vite-inertia
> cd vite-inertia
> npx @preset/cli apply laravel:inertia
```

However, after running `npx @preset/cli apply laravel:inertia` I get the following:
```
$ npx @preset/cli apply laravel:inertia
Unexpected token {
```

**Comment by innocenzi** [comment]
Works properly on my end. What Node version are you using?

**Comment by matthewknill** [comment]
Ah yes, it looks like I was using a quite outdated version of Node `v10.19.0`, updating seems to fix the issue.

Cheers
