### ISSUE TITLE
Vite manifest not found at: /home/???????/cart_shop/public/build/manifest.json

### ISSUE THREAD

**Issue by sumer5020** [innocenzi/laravel-vite#296]
I Working on project that working with laravel 9 and Vite with  laravel-vite,
In Dev environment all thing working fine, but in production cPanel server I has this issue

```
Vite manifest not found at: /home/???????/cart_shop/public/build/manifest.json

# With 

Missing Vite Manifest File
Did you forget to run `npm install && npm run dev`?
```
I tried to solve the problem but nothing work, I need to change the public folder and the sup folder build file place  from vite.config.js but I don't find the way to do that.

Note that: the file sequence is changed in cPanel shared server from 
```
- home
    - public_html
        - cart_shop
           - Root
           - public
           - etc
```

To 

```
- home
    - public_html
       - public files and folders  // I changed the index URLs too.
- cart_shop
    - Root
    - etc
```

**Comment by innocenzi** [comment]
Can you check https://github.com/innocenzi/laravel-vite/tree/feat/custom-manifest-path if that fits your use case?

You would do this in a service provider:

```php
Vite::findManifestPathWith(function (Configuration $configuration) {
    // Custom manifest path generation logic
    $buildPath = $configuration->getConfig('build_path');

    return base_path($buildPath . '/public_html/manifest.json'); // adapt for your needs
});
```

**Comment by sumer5020** [comment]
Dear @innocenzi 
where I can Add this configuration .

**Comment by innocenzi** [comment]
Use the branch instead of the published package (look up "composer repositories"), and use the snippet above (adapt it) in `AppServiceProvider`.

**Comment by innocenzi** [comment]
@sumer5020 did it work?

**Comment by sumer5020** [comment]
> @sumer5020 did it work?

Yup, many thanks bro.
