### ISSUE TITLE
[vite:laravel:config] Could not read configuration: EISDIR: illegal operation on a directory

### ISSUE THREAD

**Issue by laudaikinhdi** [innocenzi/laravel-vite#299]
I using multiple configs when I running command: npx vite --config vite.frontend.config.js
I see error:

error when starting dev server:
Error: [vite:laravel:config] Could not read configuration: EISDIR: illegal operation on a directory, read
    at readConfig (E:\laragon\www\tanmnt\larajs-2.0\node_modules\vite-plugin-laravel\dist\index.cjs:331:11)
    at Object.config (E:\laragon\www\tanmnt\larajs-2.0\node_modules\vite-plugin-laravel\dist\index.cjs:194:22)
    at resolveConfig (file:///E:/laragon/www/tanmnt/larajs-2.0/node_modules/vite/dist/node/chunks/dep-c6273c7a.js:62432:33)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async createServer (file:///E:/laragon/www/tanmnt/larajs-2.0/node_modules/vite/dist/node/chunks/dep-c6273c7a.js:59000:20)
    at async CAC.<anonymous> (file:///E:/laragon/www/tanmnt/larajs-2.0/node_modules/vite/dist/node/cli.js:699:24)
    
    
![image](https://user-images.githubusercontent.com/34116228/181224737-9b4c1902-0944-428e-953b-5a1804f0233e.png)
![image](https://user-images.githubusercontent.com/34116228/181224759-8698b976-6f86-4369-b880-9ffad888f6d6.png)

**Comment by innocenzi** [comment]
Can you set the `DEBUG` env variable to `vite:laravel:config` and copy over the logs? Also what happens if you don't specify the config as a parameter to the `laravel` plugin, but just use `--config` with the CLI?

**Comment by laudaikinhdi** [comment]
The config default is working
![image](https://user-images.githubusercontent.com/34116228/181229827-86e8e4ef-0cd1-4c33-b9c0-3bca835e5680.png)
![image](https://user-images.githubusercontent.com/34116228/181229903-a244f386-b389-4157-8e99-22e2a429269a.png)

**Comment by laudaikinhdi** [comment]
@innocenzi Can you help me? I don't solution yet :(

**Comment by innocenzi** [comment]
I can if you give me the logs I asked in my previous response ^^

Additionally, your default config's `build_path` option should not be `build`, but something like `build/default` or whatever fits for your use case.

The issues seems to be that for some reason, the plugin has a directory instead of a file as its `config` parameter.

**Comment by laudaikinhdi** [comment]
Hi @innocenzi 
I did find a solution. I did change the name config "frontend" to "frontend-office" is working. If the name "frontend" then error :D

**Comment by laudaikinhdi** [comment]
Also, Can I put the file "vite.frontend-office.config.js" in the frontend folder?
I see an error when put file "vite.frontend-office.config.js" in frontend folder
<img width="344" alt="image" src="https://user-images.githubusercontent.com/34116228/184168166-a36d23f4-4717-4226-9d7f-2f5f8c5baba4.png">
<img width="1188" alt="image" src="https://user-images.githubusercontent.com/34116228/184168906-36d0d5b8-22bd-406e-b86c-74fd6460a281.png">
