### ISSUE TITLE
resolvePageComponent maybe cause import incorrect component

### ISSUE THREAD

**Issue by andyyou** [innocenzi/laravel-vite#301]
The docs topic in [Vite with Inertia](https://laravel-vite.dev/guide/extra-topics/inertia.html) of Extra topics.

In **Example implementation** section the sample code as follow

```ts
function resolvePageComponent(name: string, pages: Record<string, any>) {
  for (const path in pages) {
    if (path.endsWith(`${name.replace('.', '/')}.vue`)) {
      return typeof pages[path] === 'function'
        ? pages[path]()
        : pages[path]
    }
  }

  throw new Error(`Page not found: ${name}`)
}
```

It's may meet the problem that loads the wrong component. Let's say I have two components `Post/Index` and `Administrator/Post/Index` one for the client and one for the dashboard. 

Only using `endsWith` will cause wrong behavior.

**Comment by innocenzi** [comment]
Hey, I'm aware of that issue - it came with Vite 3 - I forgot to change the snippet in the docs. I'll update it, thanks for the heads up.
