### ISSUE TITLE
Asset URL compatibility with development server

### ISSUE THREAD

**Issue by innocenzi** [innocenzi/laravel-vite#31]
First, the project is generated and setup/configured like so:
```bash
laravel new laravel-vite-assets
cd laravel-vite-assets
npx apply laravel:vite
php artisan vendor:publish --tag=laravel-vite-config
```

Next, I configure a dev URL in `config/vite.config` to prevent any cross-origin issues coming up since I'm using Valet
```php
'dev_url' => env('APP_URL') . ':3000'; // `http://laravel-vite-assets.test:3000`
```

Then I add an image resource located at `resources/img/logo.png` and load the image in the `HelloWorld.vue` component provided by the template in `resources/views/components/HelloWorld.vue`:
```vue
<template>
    <img src="../../img/logo.png" alt="logo">
    <h1>{{ msg }}</h1>
    ...
```

Finally, after serving the development server using `npm run dev`, the project can be viewed at `http://laravel-vite-assets.test` where we obtain the result:
![image](https://user-images.githubusercontent.com/13006946/108863005-c38d8580-75be-11eb-9f50-db5ef4431a37.png)

Using the inspector window, the image's `src` can be modified by hand here to `src="http://laravel-vite-assets.test:3000/resources/img/logo.png"`, at which point the image is served and displayed correctly.

I've been reading and searching around a lot, but the only information I've found on this had to do with the `base` property in the Vite config, which I found you implemented using the `ASSET_URL` environment variable instead. Unfortunately I've had no luck with my experimentation using this/these properties.

_Originally posted by @SirDavidLudwig in https://github.com/innocenzi/laravel-vite/discussions/28#discussioncomment-397879_

**Comment by SirDavidLudwig** [comment]
I wanted to quickly point out, it appears that `ASSET_URL`/`base` does do what I expected it to do, but it only does so on a production build, it does not do it in the dev server. Built js/css files do contain the expected URL prefix. Still hunting/experimenting!

**Comment by innocenzi** [comment]
Yup, that's what I thought as well (see https://github.com/innocenzi/laravel-vite/discussions/28#discussioncomment-397960). Might be easier to fix than expected, I'll check this out tonight. Thanks for the insights :)

**Comment by SirDavidLudwig** [comment]
Really I think this issue resides on Vite's end at this point. [They explicitly strike out external URL usage in dev servers.](https://github.com/vitejs/vite/blob/27785f7fcc5b45987b5f0bf308137ddbdd9f79ea/packages/vite/src/node/config.ts#L479) I'll work on reporting an issue to them to maybe get that worked out. At the moment, static assets can't really be handled correctly when working with a backend. For now any assets will just have to be placed in either the public or storage directories directly.

https://github.com/vitejs/vite/blob/27785f7fcc5b45987b5f0bf308137ddbdd9f79ea/packages/vite/src/node/config.ts#L479

**Comment by innocenzi** [comment]
I was investigating and I think I was coming to that conclusion as well. At first I thought that I should set the `base` option to the `dev_url`, or manually import them, but their URLs weren't being transformed. 

Let's keep the issue open while we have more information.

**Comment by Rasool-deldar** [comment]
Hello, good morning, is this problem solvable? I got a 404 error in the dev mode of the files in the resources folder.

![image](https://user-images.githubusercontent.com/58503211/116506083-b730ec00-a8d1-11eb-9659-ec928903f05e.png)

**Comment by SirDavidLudwig** [comment]
I have what I believe to be a decent workaround for now that I just realized I never posted a link to. If you required the use of static assets, the solution I posted [here](https://github.com/vitejs/vite/pull/2254#issuecomment-796201048) has worked quite well for me.

**Comment by wfisk** [comment]
I am not sure if this is related but I was having an issue loading fonts, using @font-face and scss.  In development, the path in the url() was not converted to use http://localhost:3000.  To solve this I have declared a SASS variable `$path-to-fonts` and `$path-to-webfonts` in the vite config file.  The variable is dependent on command==='serve', which is true in development mode.

Here is my vite config file
```
// vite.config.js
import { defineConfig } from 'laravel-vite';
import svelte from '@sveltejs/vite-plugin-svelte';

export default ({ command, mode }) => {
  const additionalData =
    command === 'serve'
      ? `$path-to-fonts: "http://localhost:3000/fonts"; $path-to-webfonts: "http://localhost:3000/webfonts";`
      : `$path-to-fonts: "/survey-tools/build/fonts"; $path-to-webfonts: "/survey-tools/build/webfonts";`;

	console.log({ command, mode, additionalData });

  return defineConfig({
    css: {
      preprocessorOptions: {
        scss: {
          additionalData,
        },
      },
    },
    plugins: [svelte({})],
  });
};
```
and here is the fonts.scss file:
```
@font-face {
  font-family: 'Roboto';
  src:     url('#{$path-to-fonts}/Roboto/Roboto-Light.ttf') format('truetype');
  font-weight: 300;
  font-style: normal;
  font-variant: normal;
}
```

Now I have all my fonts stored under `/resources/static/fonts` and `/resources/static/webfonts`.  On build they all get copied to `/public/build`.

**Comment by innocenzi** [comment]
Yeah this is definitely related. I'll go see if I can work around this issue more generally with the callback syntax.

**Comment by jonagoldman** [comment]
Upstream issue seems to be closed. Any updates on this?

**Comment by innocenzi** [comment]
I couldn't follow the changes since I didn't use Laravel since a while and until next month. I can see https://github.com/vitejs/vite/pull/918 has been merged, looks like the last comment gives the solution? 

If yes, I'll update the NPM package for this integration accordingly.

**Comment by innocenzi** [comment]
Note for everyone reading this, my personal workaround right now is the following: 

```php
// routes/web.php

Route::fallback(function (string $path) {
    if (! App::environment('local') || ! str_starts_with($path, 'resources')) {
        abort(404);
    }

    return Redirect::to(config('vite.dev_url') . '/' . $path);
});
```

While not ideal and quite slow, it's better than nothing.

**Comment by khalwat** [comment]
@innocenzi this might be useful to you:

https://nystudio107.com/blog/using-vite-js-next-generation-frontend-tooling-with-craft-cms#vite-processed-assets

Issue ref: https://github.com/vitejs/vite/issues/2394

**Comment by innocenzi** [comment]
@khalwat thanks! I'll see what I can do with that

**Comment by innocenzi** [comment]
Thanks @khalwat! Your workaround is now enabled by default with this plugin. I updated the docs accordingly. :)

**Comment by khalwat** [comment]
Glad it was helpful. I may turn this into a published plugin at some point, if they don't plant to resolve it in core (which seems likely).

**Comment by innocenzi** [comment]
They might solve this soon enough actually! https://github.com/vitejs/vite/pull/4337#issuecomment-885710791

**Comment by saibotk** [comment]
Sadly the workaround does not help with imported fonts (and yes i adjusted the asset_plugin rule).
Somehow it won't fix the paths for the font urls....

**Comment by innocenzi** [comment]
What's your `asset_plugin.find_regex` and import looking like?
