### ISSUE TITLE
Laravel npm run watch error while refreshing Vite

### ISSUE THREAD

**Issue by emco83** [innocenzi/laravel-vite#312]
I'm using the latest Laravel 9 that comes with Vite, instead of Mix. Vite works much faster than Mix but there's one very annoying issue.

In package.json I've the following line, so I can use the regular 'npm run watch' as I had on Mix. Here's my code:

```
"scripts": {
    "dev": "vite",
    "build": "vite build",
    "watch": "vite build --watch"
},
```
I work on production server, so I don't need 'npm run dev' and instead of that I'm using 'npm run build'. So far so good, now the issue:

When I write 'npm run watch' while the process is running, I'm getting the error on the browser:

```
    Vite manifest not found at:
/home/username/public_html/cms/public/build/manifest.json
```
The marked error is this line:

`@vite(['resources/sass/app.scss', 'resources/js/app.js'])`

When the process is finished, the error is gone and the changes are applied.

If I change something in my CSS again, the same error appears while it's processing.

When I was using Mix in my other projects there wasn't any error when I write "npm run watch", I just wait for the changes to apply without any error while processing.

Is there any solution for this?

**Comment by innocenzi** [comment]
This is unrelated to this package, you seem to use the official Vite integration. See their own  docs: https://laravel.com/docs/9.x/vite#main-content

I think you can probably solve your issue by setting [this option](https://vitejs.dev/config/build-options.html#build-emptyoutdir) in `vite.config.ts` though.

**Comment by emco83** [comment]
Hello,

Thank you for your answer. I've tried your suggestion but the issue still remains.

Here's my code of `vite.config.js`:
```
import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';

export default defineConfig({
    plugins: [
        laravel({
            input: [
                'resources/sass/app.scss',
                'resources/js/app.js',
            ],
            build: {
                emptyOutDir: false,
            },
            refresh: true,
        }),
    ],
});
```

**Comment by emco83** [comment]
Thank you very much for your help, that actually fixed the issue!

I'm sorry for posting in the wrong repository but at least there's a right person to help here. :)
