### ISSUE TITLE
Innocenzi Vite facade conflicts with Laravel Vite facade

### ISSUE THREAD

**Issue by prattcmp** [innocenzi/laravel-vite#316]
### Error/Problem:
Innocenzi's Vite facade conflicts with Laravel's new Vite facade, which now comes by default with the Laravel framework.

<img width="1381" alt="Screen Shot 2022-09-12 at 6 04 35 PM" src="https://user-images.githubusercontent.com/1497950/189784959-cca2eabf-a2f5-4209-a190-a8670a1f7870.png">

### Suggested Change:

**Replace:**
https://github.com/innocenzi/laravel-vite/blob/9ec139ab115d7a93def1607d4291b6ce49c5839b/composer.json#L54-L63

**By removing the alias in the `innocenzi/laravel-vite` package:**
```
	"extra": {
		"laravel": {
			"providers": [
				"Innocenzi\\Vite\\ViteServiceProvider"
			]
		}
	},
```

### Current Workaround:

1. Disable autoload for `innocenzi/laravel-vite` in **user's** `composer.json`:
```
    "extra": {
        "laravel": {
            "dont-discover": [
                ...,
                "innocenzi/laravel-vite"
                ...,
            ]
        }
    },
```
2. Manually add service provider in **user's** `config/app.php`:
```
    'providers' => [
        ...,
        Innocenzi\Vite\ViteServiceProvider::class,
        ...,
    ],
```
3. Flush autoload by running: `php artisan clear-compiled`
4. Re-dump autoload by running: `composer dump-autoload`

**Comment by innocenzi** [comment]
`Vite::asset` is not something that is valid using the facade from this package. I also can't seem to reproduce that issue. If you can create a valid reproduction I ll gladly take a look.
