### ISSUE TITLE
Inertia Vite preset not working

### ISSUE THREAD

**Issue by TeaDrinkingProgrammer** [innocenzi/laravel-vite#317]
I am trying to create a new project using Laravel, Vite and Inertiajs, following [the preset instructions in the documentation](https://laravel-vite.dev/guide/extra-topics/inertia.html#overview).I got an error when running the following command: "npx @preset/cli apply laravel:inertia --no-tailwindcss".
![image](https://user-images.githubusercontent.com/20358521/189930933-0844b160-a212-44f2-b60c-d50385d83fc2.png)
When I try to run npm run dev and access the page, it is blank.

**Comment by innocenzi** [comment]
Works fine for me. The version mismatch is just a warning, it's not an error. All preset work. If you are trying to access the page via `http://localhost:3000`, don't. You need `php artisan serve`, Valet or another webserver, like you would without Vite 👍

**Comment by innocenzi** [comment]
Ah, nevermind, seems like the `--no-tailwindcss` does break the preset.

**Comment by TeaDrinkingProgrammer** [comment]
Ah okay. I didn't know that you should use php artisan serve. I am new to laravel and the script ends with a comment which says you should use npm run dev
