### ISSUE TITLE
Compatible with Laravel 10

### ISSUE THREAD

**Issue by weblabio** [innocenzi/laravel-vite#343]
Hi, I see there is support for version 10 in the main branch, but couldn't find a release version (latest 0.2.2) that supports 10.

From the documentation the command `composer require innocenzi/laravel-vite` returns an error
```
 Problem 1
    - innocenzi/laravel-vite[0.0.1, ..., 0.1.22] require illuminate/contracts ^8.0 -> found illuminate/contracts[v8.0.0, ..., v8.83.27] but these were not loaded, likely because it conflicts with another require.
    - innocenzi/laravel-vite[0.1.23, ..., v0.2.2] require illuminate/contracts ^8.0|^9.0 -> found illuminate/contracts[v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.0] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires innocenzi/laravel-vite * -> satisfiable by innocenzi/laravel-vite[0.0.1, ..., v0.2.2].
```

Installation from main branch successful: `composer require innocenzi/laravel-vite:dev-main`
Maybe you forgot to release a new version?

**Comment by innocenzi** [comment]
Yes I didn't release, thanks for the heads up. v0.3.1 should work!

Note: you should, if you can, migrate to the official Vite integration from the Laravel team

**Comment by weblabio** [comment]
> Yes I didn't release, thanks for the heads up. v0.3.1 should work!
> 
> Note: you should, if you can, migrate to the official Vite integration from the Laravel team

thank you very much
