### ISSUE TITLE
Complete documentation

### ISSUE THREAD

**Issue by innocenzi** [innocenzi/laravel-vite#4]
I've prepared a documentation site using VitePress, which only documents the installation process. I need to finish it.

**Comment by Wulfheart** [comment]
Awesome. Just wanted to point out that there is currently a guide missing on how to build the assets for production.

**Comment by innocenzi** [comment]
Yes. I need to finish writing the docs, which I'll do after I finish up with the other issues. On this topic, I just added support for `ASSET_URL`, which *should* bring support for deployment on Vapor.
