### ISSUE TITLE
[ error ]  Could not clone laravel-presets/vite. Host key verification failed

### ISSUE THREAD

**Issue by boussadjra** [innocenzi/laravel-vite#48]
I've installed new laravel project using the following command : 

  `composer create-project laravel/laravel twelve`

without doing any change in this fresh project I ran : 

  `npx apply laravel:vite`

I get the following error : 

![image](https://user-images.githubusercontent.com/11801238/109297045-ab716c80-7831-11eb-99b2-e8a083e79c08.png)

**Comment by innocenzi** [comment]
Hey, looks like there is an issue with your SSH setup. Make sure you have an SSH key, configured your SSH agent, and linked the key to your GitHub account. 

In the meantime, you can do `npx apply laravel:vite --no-ssh` instead.
