### ISSUE TITLE
Make asset URLs secure

### ISSUE THREAD

**Issue by innocenzi** [innocenzi/laravel-vite#54]
The tags are always output as `http`. Making a `secure` config option that can use for the `asset` helper, will make this possible

ManifestEntry.php - Line 60-66
```php
/**
 * Gets the complete path for the given asset path.
 */
protected function asset(string $path): string
{
    return asset(sprintf('/%s/%s', config('vite.build_path'), $path), config('vite.secure'));
}
```

_Originally posted by @TobiasGraml11 in https://github.com/innocenzi/laravel-vite/discussions/53_

**Comment by innocenzi** [comment]
@TobiasGraml11 What's your use case for this? The `asset` helper already uses your current URL as well as its scheme. Do you need the granularity for an edge case?

**Comment by TobiasGraml11** [comment]
Hello @innocenzi !
Are you sure it uses the protocol as well? Maybe an oversight by me.
When I "deploy" it, it always uses http, even when I use https.

And I already tried to create a branch/PR when writing this issue, but did not have permissions.

**Comment by innocenzi** [comment]
> Are you sure it uses the protocol as well? Maybe an oversight by me. 
Not sure if you don't set an `ASSET_URL`, but if you do it uses it.

> And I already tried to create a branch/PR when writing this issue, but did not have permissions.
You need to fork, and then PR. But before you PR, please make sure this is actually needed

**Comment by TobiasGraml11** [comment]
Sure thing, will check it on Monday

**Comment by TobiasGraml11** [comment]
Hello @innocenzi!

Thanks for your tip about the `ASSET_URL`, this fixes my issue!
I guess this can be closed without any code change.

**Comment by innocenzi** [comment]
Glad it works for you!
