### ISSUE TITLE
Artisan unable to locate and publish `vite.php` config file

### ISSUE THREAD

**Issue by SirDavidLudwig** [innocenzi/laravel-vite#55]
It seems that when executing the command below found in the [docs](https://laravel-vite.netlify.app/guide/configuration.html#publishing-the-configuration) to generate the `vite.php` config file:

```sh
php artisan vendor:publish --tag=laravel-vite-config
```

results in an error stating: `Unable to locate publishable resources`. I just tested it on both Linux and Mac using the latest versions of Laravel and Laravel-Vite applied using the `npx` preset and this error is present on both machines.

**Comment by innocenzi** [comment]
Hey, there was a breaking change in `laravel-package-tools` that make this break (https://github.com/spatie/laravel-package-tools/commit/13f3b0ffcf3c525900eb5cdf945118d6b2cb4720). You need to use `php artisan vendor:publish --tag=vite-config` now, I'll update the docs accordingly.
