### ISSUE TITLE
Application works locally, but when deployed gives "Set-Cookie header is ignored in response from url" errors

### ISSUE THREAD

**Issue by shealan** [innocenzi/laravel-vite#59]
The application is working beautifully on my machine using your package. Thank you! However, when I deploy it seems to have introduced some strange issues with the API communication code I have.

I am using InertiaJS and Vue.

When I attempt to do some javascript CRUD operations that work fine locally, I get these odd console warnings that are blocking the operation. "Set-Cookie header is ignored in response from url. Cookie length should be less than or equal to 4096 characters."

The application worked fine when I was using Laravel Mix (which your package is replacing).

This is my config:

```js
import { defineConfig } from 'laravel-vite'
import { createVuePlugin as Vue2Plugin } from 'vite-plugin-vue2'

export default defineConfig({
  plugins: [
    Vue2Plugin()
  ],
  optimizeDeps: {
    include: [
      'vue',
      'portal-vue',
      '@inertiajs/inertia',
      '@inertiajs/progress',
      'axios'
    ]
  }
})
```

I tried removing the 'optimizeDeps' to see if it was somehow messing these up but it made no difference.

Because these are warnings, not errors, I'm not sure how to go about troubleshooting.

**Comment by innocenzi** [comment]
Hi there, 

I don't think this has anything to do with Vite, but I'll be happy to help you debug this. Can you provide me with some more details? Something useful would be the code which triggers this error, and the HTTP request that you see in your devtools. 

The error you are getting is related to the maximum possible cookie size, which means that you're probably storing something too big in one cookie. 

What session driver are you using? I suggest you try to use the [database session driver](https://laravel.com/docs/8.x/session#configuration) in production just to test if the error comes from that.
