### ISSUE TITLE
System is not defined, when using @vitejs/plugin-legacy

### ISSUE THREAD

**Issue by game5413** [innocenzi/laravel-vite#61]
Hello, thanks for create this preset to integrating with laravel. I found bug that broken (i think), when using [@vitejs/plugin-legacy](https://github.com/vitejs/vite/tree/main/packages/plugin-legacy#readme) `@vite` helper not automatically insert fallback to resolve the SystemJS import.

![image](https://user-images.githubusercontent.com/37659721/112722736-c4a72f00-8f3d-11eb-9100-a499461d3c2d.png)

In the current version Vite, the fallback was inserted automatically solve that problem, the first and last scripts tag wasn't available.

![image](https://user-images.githubusercontent.com/37659721/112722786-0506ad00-8f3e-11eb-8b38-a91f74ed2b63.png)

And last, i think when building for production version vite not polyfill the scripts, but just doing the compiling.

Standalone Vite
![image](https://user-images.githubusercontent.com/37659721/112722916-9c6c0000-8f3e-11eb-85be-678eabdcd53f.png)

Laravel-Vite
![image](https://user-images.githubusercontent.com/37659721/112722922-a988ef00-8f3e-11eb-9b8c-23294bd9a01f.png)

Both using same configuration for Vite, but different import.
![image](https://user-images.githubusercontent.com/37659721/112723030-261bcd80-8f3f-11eb-8a38-defec9387fd0.png)

Laravel Version: 8.34.0
Vite Version: ^2.1.3
@vitejs/plugin-legacy: ^1.3.2
laravel-vite: 0.0.7

**Comment by innocenzi** [comment]
Hello, yes, this is tracked in https://github.com/innocenzi/laravel-vite/issues/30. I plan on working on it as soon as the asset issue is resolved upstream, so I can work on everything at once. Hopefully we won't wait too long!
