### ISSUE TITLE
process.env.NODE_ENV replaced with "development" in bundled package

### ISSUE THREAD

**Issue by amyisme13** [innocenzi/laravel-vite#66]
So after being very confused on why even after setting NODE_ENV to production the build_path is still not appended. I've found that the process.env.NODE_ENV is replaced with "development" which I'm sure is not the intention of that line.

As you can see between here
https://github.com/innocenzi/laravel-vite/blob/11d9fde321cf2ae515b79969e99bae7f5fcc506a/npm/src/index.ts#L56
and in the bundled package here (line 25)
https://unpkg.com/browse/laravel-vite@0.0.7/dist/index.js

The solution would be to update tsup to v4. Hopefully nothing break as it is a major update 😅
https://github.com/egoist/tsup/releases/tag/v4.0.0

**Comment by innocenzi** [comment]
Hey, I updated the NPM package, you can install `laravel-vite@0.0.8`. Thank you!
