### ISSUE TITLE
Handle HMR on Blade files

### ISSUE THREAD

**Issue by innocenzi** [innocenzi/laravel-vite#7]
Last time I tried it didn't seem to work. Apparently chokidar is configured to watch the entire project from the root (except `node_modules` and `.git`), so it might be the HMR handler that decides not to do a full reload. 

Maybe adding a handler for this in the plugin is needed. 

Reference: 
- https://github.com/vitejs/vite/blob/9af1517e47f66bb793447d998cf1a4d2fa3ef758/packages/vite/src/node/server/hmr.ts#L38

**Comment by Wulfheart** [comment]
Does it also reload the page when I’m updating a blade view?

**Comment by innocenzi** [comment]
Yes, it does a full-page reload when you edit `.blade.php` files. For other files, it is handled by Vite, so if you edit a Vue file it does a partial reload like expected.
