### ISSUE TITLE
Dynamic imports not working for react

### ISSUE THREAD

**Issue by notf0und** [innocenzi/laravel-vite#80]
Hi, first of all I wanna say thank you for this amazing package, it made my life easier.

### Description
Here for reporting a bug when using lazy load for react. Vite detects them properly and split the code, but on the references to the splited files on the entry point, they have the path like "/assets/SomeComponent.hash.jsx" but it has to be "/build/assets/SomeComponent.hash.jsx"

This issue just exists on the build. On dev, the issue doesn't exist and application resolves paths as expected.

### Reproduce the issue

```jsx
// resources/js/app/Pages/Users.jsx
import React from 'react';

const Users = () => <div>users</div>;
export default Users;
```
```jsx
// resources/js/app/Pages/Models.jsx
import React from 'react';

const Models = () => <div>models</div>;
export default Models;
```

```jsx
// resources/js/app/Routes.jsx
import React, { Suspense } from 'react';
import { Redirect, Route, Switch } from 'react-router-dom';


export const resources = [
  'Users',
  'Models',
];

const Routes = () => {
  const routes = resources.map((resource) => {
    const Resource = React.lazy(() => new Promise((resolve) => resolve(import(`./Pages/${resource}.jsx`))));
    return <Route key={resource} path={`/${resource.toLowerCase()}`} component={Resource} />;
  });

  return (
    <Suspense fallback={null}>
      <Switch>
        {routes}
      </Switch>
    </Suspense>
  );
};

export default Routes;
```

```jsx
// resources/js/app/App.jsx
import React from 'react';
import { BrowserRouter } from 'react-router-dom';
import Routes from './Routes';

const App = () => (
  <BrowserRouter>
    <Routes />
  </BrowserRouter>
);

export default App;
```

I tried to figure out how to solve it, but spent a good amount of time with it and didnt't found any proper solution, so I ended up just creating a redirection for a request to public/assets to go to public/build/assets.

```php
// routes/web.php
Route::get('/assets/{path?}', fn ($path) => redirect('/build/assets/' . $path));

```

**Comment by innocenzi** [comment]
Hey, thanks for reporting this. Can you show me your `config/vite.php` and `vite.config.ts`? I need to figure out if this is an issue in your config, or in the default one this package provides.

**Comment by innocenzi** [comment]
I'd also appreciate a repository with a reproduction, so I can check it out (I've never set up a React app and I don't know what `React.lazy` does). I've seen a few issues related to that in the Vite repository, so maybe that's an upstream issue.

**Comment by notf0und** [comment]
I was trying to set up a minimal repository for issue replication and the issue wasn't coming, ended up discovering that the issue is introduced by [VitePluginImp](https://github.com/onebay/vite-plugin-imp) plugin.

I'm closing this issue as nothing to be fixed on this package.
