### ISSUE TITLE
Overwrites tsconfig.json on every execution.

### ISSUE THREAD

**Issue by henriquecm** [innocenzi/laravel-vite#87]
Related to #71 but I am case I already have a tsconfig.json and every time I execute the script it gets overwritten, for now I am disabling like you suggested, but I think ideally it should just the related entry and not replace the whole file.

**Comment by innocenzi** [comment]
Hey, if the `tsconfig.json` exists it doesn't get replaced, but the `paths` get merged with the ones generated from your config. `baseUrl` does get overwritten though, but that's it. 

Can you describe exactly what bothers you and how you'd want the `tsconfig` alias generation to behave?

**Comment by henriquecm** [comment]
Basically this happens.

![image](https://user-images.githubusercontent.com/15136037/126247538-85a00da6-ea04-47d3-ab6f-8a65e0a5df6a.png)

I wasn't paying attention the first time so I ended up commiting it, but still every time I execute "dev" or "build" this is what happens.

I was migrating this project from laravel-mix to vitejs, so I still have to clean the tsconfig.json, but I use vue2 with class decorators so I need some of these options.

**Comment by innocenzi** [comment]
Well I'm not sure what's happening honestly. If the `tsconfig.json` didn't exist, it'd add more `compilerOptions` than that, so it finds the `tsconfig.json` but can't parse its contents maybe? 

What kind of development environment do you have? Local filesystem? Docker?

Can you debug `vendor\innocenzi\laravel-vite\src\Commands\GenerateAliasesCommand.php` by `dd()`ing line 48?

What happens if you run `php artisan vite:aliases` manually?

**Comment by henriquecm** [comment]
> What kind of development environment do you have? Local filesystem? Docker?

Local

> What happens if you run php artisan vite:aliases manually?

 [OK] The tsconfig.json file has been updated.   

> Can you debug vendor\innocenzi\laravel-vite\src\Commands\GenerateAliasesCommand.php by dd()ing line 48?

null, the `File::get` is working but the json_decode returns null
`json_last_error_msg` returns Syntax error.
I tried a online json validator and found out the reason, trailing commas.
Probably would be better to throw a error instead of overwriting the file.

**Comment by innocenzi** [comment]
Latest release will throw an error so it's less confusing. 👍

**Comment by henriquecm** [comment]
Thanks for the help
