### ISSUE TITLE
Wrong prefix for relative modules

### ISSUE THREAD

**Issue by exodusanto** [innocenzi/laravel-vite#89]
Hi, using npm package `0.0.15` I notice a problem for assets loading.

I think that vite configuration have some problem on local env.

Using version `0.0.14` vite request module using this tag and this src
```html
<link rel="modulepreload" as="script" crossorigin="" href="/build/assets/vendor.42458bdd.js">
```

Since `0.0.15` the src is
```html
<link rel="modulepreload" as="script" crossorigin="" href="/assets/vendor.42458bdd.js">
```

I problem maybe can be in this [change](https://github.com/innocenzi/laravel-vite/commit/1cb2f28e8eb8c0204826845e6a06dd46cf1f4345#diff-301ffe3d681dfd02094b929ec3afc58bf7f809b24dfa55f97772dbcfac907709L59-R82)

**Comment by innocenzi** [comment]
Hey, sorry, I don't understand the issue. Can you explain in better terms the scenario and the problem occurring?

**Comment by exodusanto** [comment]
Sure,
In page `head` section, with npm package `laravel-vite:0.0.14`, the `@vite` blade tag inject into the view `link` and `script` tags to boot js.

```html
<link rel="stylesheet" href="https://mydomaintest/build/assets/main.eb54cfaf.css">
<script type="module" src="https://mydomain.test/build/assets/main.0a566646.js"></script>
```

And after the initial boot vite starts to inject other modules using relative path
```html
<link rel="modulepreload" as="script" crossorigin="" href="/build/assets/Submodule.f6b1a3d3.js">
```

Since version `0.0.15` in console I start receiving
![image](https://user-images.githubusercontent.com/13484843/127629795-b753a1b7-8d00-4f27-8ea2-d608e99db6d1.png)

And I notieced that vite autoinjected modules has a wrong relative path
```html
<!-- without /build prefix -->
<link rel="modulepreload" as="script" crossorigin="" href="/assets/Submodule.f6b1a3d3.js">
```

I tried to downgrade Vite but seems that the only problem is version `0.0.15`

**Comment by innocenzi** [comment]
Does it work like you expected if you set `assets_plugin` to `false` (instead of an array) in `config/vite.php`?

**Comment by exodusanto** [comment]
I just tried, but seems not to resolve

**Comment by innocenzi** [comment]
Ok, can you try `0.0.16`? It reverts the environment check which changes the `base`. If it isn't the issue I'll need a minimal reproduction repository.

**Comment by exodusanto** [comment]
Seems fixed now

**Comment by innocenzi** [comment]
Cool. Thanks for reporting!
