### ISSUE TITLE
Multiple separated bundles

### ISSUE THREAD

**Issue by georgeboot** [innocenzi/laravel-vite#90]
I have 2 entry points. One for front-end, one that is loaded **additionally** with admin-only code.
Currently, vite will generate a vendor bundle, but it is loaded both front-end and admin. This means that it is now pointless to use 2 separate files, as all code is loaded on both places.

Why is this? I know I can use `build.rollupOptions.output.manualChunks` but that also isn't ideal.

Perhaps the default logic of this package isn't too great or was this never made with multiple entry-points in mind? (seems like it does)

Giving the following 2 entry points:

```js
// resources/scripts/app.js
import Alpine from 'alpinejs'
import * as Sentry from '@sentry/browser'
import { Integrations } from '@sentry/tracing'
import '@/css/app.css'

Sentry.init({
    dsn: import.meta.env.VITE_SENTRY_LARAVEL_DSN,
    // other sentry options
})

window.Alpine = Alpine

Alpine.start()
```

```js
// resources/scripts/admin.js
import EasyMDE from 'easymde'
import '@/css/editor.css'
import ApexCharts from 'apexcharts'

window.EasyMDE = EasyMDE
window.ApexCharts = ApexCharts
```

And this vite config:
```ts
import { defineConfig } from 'laravel-vite'
import copy from 'rollup-plugin-copy'

const copyPlugin = copy({
    targets: [
        { src: 'resources/images/**/*', dest: 'public/images' },
    ],
})

export default defineConfig()
    .withValetCertificates({ domain: 'my-app.test' })
    .withPlugin(copyPlugin)
```

The following `manifest.json` is generated:

```json
{
  "resources/scripts/admin.js": {
    "file": "assets/admin.b5d5c906.js",
    "src": "resources/scripts/admin.js",
    "isEntry": true,
    "imports": [
      "_vendor.70ec0c88.js"
    ],
    "css": [
      "assets/admin.49a60138.css"
    ]
  },
  "resources/scripts/app.js": {
    "file": "assets/app.3d144d5c.js",
    "src": "resources/scripts/app.js",
    "isEntry": true,
    "imports": [
      "_vendor.70ec0c88.js"
    ],
    "css": [
      "assets/app.3ac4d7e9.css"
    ]
  },
  "_vendor.70ec0c88.js": {
    "file": "assets/vendor.70ec0c88.js"
  }
}
```

**Comment by innocenzi** [comment]
Hey, yes, the defaults for this package weren't thoughts for multiple bundles. I'm not even sure how to do this with Vite. 

If you can provide me with a working configuration for generating multiple bundles, I can look into abstracting that and including it in Laravel Vite

**Comment by georgeboot** [comment]
For now I went with `build.rollupOptions.output.manualChunks = null`, which only extracts the `commonjsHelpers` into a separate bundle.

My vote would be to make this the out-of-the-box experience, as it doesn't do any unexpected things.

**Comment by innocenzi** [comment]
Yeah I'd like to as well, but as far as I read from the docs and the issues, it isn't possible - I'll have to experiment when I have time.
