### ISSUE TITLE
error npx apply laravel:vite

### ISSUE THREAD

**Issue by Rasool-deldar** [innocenzi/laravel-vite#91]
npx apply laravel:vite
[ info ]  Applying preset laravel:vite.
[ error ]  Could not clone laravel-presets/vite.
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Please resolve this issue

**Comment by innocenzi** [comment]
> Host key verification failed.
> Please make sure you have the correct access rights and the repository exists.

Use `--no-ssh`, but you should setup an SSH key instead. https://docs.github.com/en/github/authenticating-to-github/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account
