### ISSUE TITLE
SSL bug when using valet certs.

### ISSUE THREAD

**Issue by atymic** [innocenzi/laravel-vite#92]
Repro:

- Run `valet secure` to setup fresh cert.
- Add `.withValetCertificates('appname.test')` to config file
- Run `yarn dev` 

```
error when starting dev server:
Error: error:0909006C:PEM routines:get_name:no start line
    at node:internal/tls/secure-context:65:13
    at Array.forEach (<anonymous>)
    at setCerts (node:internal/tls/secure-context:63:3)
    at configSecureContext (node:internal/tls/secure-context:152:5)
    at Object.createSecureContext (node:_tls_common:116:3)
    at Http2SecureServer.Server.setSecureContext (node:_tls_wrap:1344:27)
    at new Server (node:_tls_wrap:1203:8)
    at new Http2SecureServer (node:internal/http2/core:3108:5)
    at Object.createSecureServer (node:internal/http2/core:3299:10)
    at resolveHttpServer (/Users/user/code/edgility/smsapi/node_modules/vite/dist/node/chunks/dep-c1a9de64.js:58173:33)
```

Can chuck you contents of cert files via email if req since they are just dev.
Latest valet, node 16.5, latest npm lib vers

**Comment by atymic** [comment]
https://github.com/laravel/valet/blob/d312a588f352c4b5c62b75c4abd1897403b04b76/cli/includes/helpers.php

Seems to be using old path?
Correct path should be `~/.config/valet/Certificates`

**Comment by innocenzi** [comment]
Hey, 

Make sure everything is up to date for you. `laravel-vite` should be `0.0.16`

> Correct path should be `~/.config/valet/Certificates`

It's the case since https://github.com/innocenzi/laravel-vite/pull/85. 

> Add .withValetCertificates('appname.test') to config file

`.withValetCertificates('appname.test')` should be `.withValetCertificates({ domain: 'appname.test' })`

Let me know if that works for you

**Comment by atymic** [comment]
Ahh, my bad. I just installed the inertia preset, i guess it it installs the wrong version? Will update, sec.

**Comment by innocenzi** [comment]
I didn't know it would strictly install the given version. I'll update the preset accordingly, thanks!

**Comment by atymic** [comment]
Sweet, works :D sorry for dumb issue, should have checked the lock file.
BTW might also be worth noting in docs that if you use valet certs you need to publish the vite config and set the URL to https:/ :)

Thanks again!

**Comment by innocenzi** [comment]
No worries, glad you got this fixed!
